# Generated by Django 6.0.1 on 2026-01-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tender_number', models.CharField(max_length=50, unique=True)),
                ('opening_date', models.DateTimeField()),
                ('closing_date', models.DateTimeField()),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed'), ('awarded', 'Awarded')], default='draft', max_length=20)),
                ('document_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tender',
                'verbose_name_plural': 'Tenders',
                'ordering': ['-created_at'],
            },
        ),
    ]
