# Generated by Django 6.0.1 on 2026-01-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenCharter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('service_type', models.CharField(choices=[('tax', 'Tax Services'), ('license', 'License Services'), ('certificate', 'Certificate Services'), ('complaint', 'Complaint Services'), ('other', 'Other Services')], max_length=50)),
                ('description', models.TextField()),
                ('processing_time', models.CharField(help_text='e.g., 7-10 working days', max_length=100)),
                ('required_documents', models.TextField(help_text='List of required documents')),
                ('fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Citizen Charter',
                'verbose_name_plural': 'Citizen Charters',
                'ordering': ['-created_at'],
            },
        ),
    ]
