# Generated by Django 6.0.1 on 2026-01-18 18:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('ID', 'National ID'), ('PASSPORT', 'Passport'), ('BIRTH_CERT', 'Birth Certificate'), ('MARRIAGE_CERT', 'Marriage Certificate'), ('OTHER', 'Other')], max_length=20, verbose_name='Document Type')),
                ('document_number', models.CharField(max_length=100, verbose_name='Document Number')),
                ('file', models.FileField(upload_to='citizens/documents/', verbose_name='Document File')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Issue Date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
            ],
            options={
                'verbose_name': 'Citizen Document',
                'verbose_name_plural': 'Citizen Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.RemoveField(
            model_name='citizen',
            name='nid',
        ),
        migrations.RemoveField(
            model_name='citizen',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='citizen',
            name='user',
        ),
        migrations.AddField(
            model_name='citizen',
            name='citizen_id',
            field=models.CharField(blank=True, help_text='Citizen identification number', max_length=20, null=True, unique=True, verbose_name='Citizen ID'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='co_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Father / Husband / Company Name'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citizens_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='marital_status',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed')], default='S', max_length=1, verbose_name='Marital Status'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Middle Name'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='national_id',
            field=models.CharField(blank=True, help_text='National identification number', max_length=20, null=True, unique=True, verbose_name='National ID'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='occupation',
            field=models.CharField(blank=True, max_length=200, verbose_name='Occupation'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+8801XXXXXXXXXX'. Up to 10 digits allowed.", regex='^\\+?8801?\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='citizen',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='citizens/photos/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddIndex(
            model_name='citizen',
            index=models.Index(fields=['national_id'], name='citizen_cit_nationa_562dcf_idx'),
        ),
        migrations.AddIndex(
            model_name='citizen',
            index=models.Index(fields=['last_name', 'first_name'], name='citizen_cit_last_na_1a0af3_idx'),
        ),
        migrations.AddField(
            model_name='citizendocument',
            name='citizen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='citizen.citizen'),
        ),
    ]
