# Generated by Django 6.0.1 on 2026-01-18 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0002_citizendocument_remove_citizen_nid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Link to user account for citizen login', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citizen_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account'),
        ),
    ]
