# Generated by Django 6.0.1 on 2026-01-18 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citizen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('birth', 'Birth Certificate'), ('death', 'Death Certificate'), ('marriage', 'Marriage Certificate'), ('character', 'Character Certificate'), ('income', 'Income Certificate'), ('residence', 'Residence Certificate')], max_length=50)),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='citizen.citizen')),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
