# Generated by Django 6.0.1 on 2026-01-18 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0001_initial'),
        ('citizen', '0002_citizendocument_remove_citizen_nid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Certification Type Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Certification Type Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Fee')),
                ('validity_days', models.IntegerField(default=365, help_text='Number of days the certificate is valid', verbose_name='Validity (Days)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Certification Type',
                'verbose_name_plural': 'Certification Types',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='certification',
            name='certificate_type',
        ),
        migrations.AddField(
            model_name='certification',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='certification',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry Date'),
        ),
        migrations.AddField(
            model_name='certification',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications_issued', to=settings.AUTH_USER_MODEL, verbose_name='Issued By'),
        ),
        migrations.AddField(
            model_name='certification',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/%Y/%m/%d/', verbose_name='PDF Certificate'),
        ),
        migrations.AddField(
            model_name='certification',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Rejection Reason'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='certificate_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Certificate Number'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='citizen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certifications', to='citizen.citizen'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Issue Date'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='certification',
            name='certification_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certifications', to='certification.certificationtype'),
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['certificate_number'], name='certificati_certifi_e1048f_idx'),
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['citizen'], name='certificati_citizen_92b2af_idx'),
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['status'], name='certificati_status_379c62_idx'),
        ),
    ]
