# Generated by Django 6.0.1 on 2026-01-18 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holdingtax', '0002_migrate_to_new_structure'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='area',
            new_name='holdingtax__name_794503_idx',
            old_name='holdingtax_a_name_idx',
        ),
        migrations.RenameIndex(
            model_name='holdingtax',
            new_name='holdingtax__tax_num_28832b_idx',
            old_name='holdingtax_h_tax_num_idx',
        ),
        migrations.RenameIndex(
            model_name='holdingtax',
            new_name='holdingtax__holding_674c61_idx',
            old_name='holdingtax_h_holding_idx',
        ),
        migrations.RenameIndex(
            model_name='holdingtax',
            new_name='holdingtax__status_41bd0b_idx',
            old_name='holdingtax_h_status_idx',
        ),
        migrations.RenameIndex(
            model_name='holdingtax',
            new_name='holdingtax__due_dat_c33202_idx',
            old_name='holdingtax_h_due_dat_idx',
        ),
        migrations.RenameIndex(
            model_name='property',
            new_name='holdingtax__propert_4885ad_idx',
            old_name='holdingtax_p_property_idx',
        ),
        migrations.RenameIndex(
            model_name='property',
            new_name='holdingtax__owner_i_b5e9a5_idx',
            old_name='holdingtax_p_owner_id_idx',
        ),
        migrations.RenameIndex(
            model_name='property',
            new_name='holdingtax__city_5e246b_idx',
            old_name='holdingtax_p_city_idx',
        ),
        migrations.RenameIndex(
            model_name='property',
            new_name='holdingtax__area_id_84f346_idx',
            old_name='holdingtax_p_area_id_idx',
        ),
        migrations.RenameIndex(
            model_name='property',
            new_name='holdingtax__street__44317b_idx',
            old_name='holdingtax_p_street_idx',
        ),
        migrations.RenameIndex(
            model_name='property',
            new_name='holdingtax__status_bb5e04_idx',
            old_name='holdingtax_p_status_idx',
        ),
        migrations.RenameIndex(
            model_name='propertyattachment',
            new_name='holdingtax__propert_04a251_idx',
            old_name='holdingtax_pa_property_idx',
        ),
        migrations.RenameIndex(
            model_name='propertyattachment',
            new_name='holdingtax__attachm_646be5_idx',
            old_name='holdingtax_pa_attachm_idx',
        ),
        migrations.RenameIndex(
            model_name='propertyattachment',
            new_name='holdingtax__uploade_c456f5_idx',
            old_name='holdingtax_pa_uploaded_idx',
        ),
        migrations.RenameIndex(
            model_name='street',
            new_name='holdingtax__name_9488d8_idx',
            old_name='holdingtax_s_name_idx',
        ),
        migrations.RenameIndex(
            model_name='street',
            new_name='holdingtax__area_id_8b3a74_idx',
            old_name='holdingtax_s_area_id_idx',
        ),
        migrations.RenameIndex(
            model_name='taxpayment',
            new_name='holdingtax__payment_155161_idx',
            old_name='holdingtax_t_payment_idx',
        ),
        migrations.RenameIndex(
            model_name='taxpayment',
            new_name='holdingtax__holding_dd7f72_idx',
            old_name='holdingtax_t_holding_idx',
        ),
    ]
